@startuml
class "ArrayReader`1"<T> {
    - arr : T[]
    - i : int
    + ArrayReader(arr:T[])
    + Peekc() : T
    + Peekc(value:T) : bool
    + Peekn() : T
    + Peekn(value:T) : bool
    + Consume(from:string) : T
    + Incr() : void
    + Incr(expected:T, ret:bool) : bool
    + Incr(expected:T[]) : void
    + set(i:int) : void
    + get() : int
    + IsEOF() : bool
    + PrintError() : void
    + PrintErrorS() : string
    + <<override>> ToString() : string
    + ContinueUntil(str:T) : void
    + LineContainsNumber() : bool
    + CountUntil(str:T) : int
}
@enduml
