@startuml
class "AstNode`1"<T> <<struct>> {
    + @type : T?
    + value : string
    + childs : List<AstNode<T>>
    + AstNode()
    + <<override>> ToString() : string
}
class "AbstractSyntaxTree`1"<T> {
    + root : AstNode<T>
    + Result : LexerResult<T>
    + ar : ArrayReader<TokenElement<T>>
    + AbstractSyntaxTree(result:LexerResult<T>)
}
@enduml
