@startuml
class ParserModule <<static>> <<partial>> {
    + {static} Alt(childs:Group_t<T>[]) : Alt_t<T>
}
class "Alt_t`1"<T> <<struct>> {
    + childs : Group_t<T>[]
    + HasToken(t:T) : bool
    + ParseElement(ar:ArrayReader<TokenElement<T>>) : AstNode<T>
}
ParserModule +-- "Alt_t`1"
"IEbnfElement`1" "<T>" <|-- "Alt_t`1"
@enduml
