@startuml
class ParserModule <<static>> <<partial>> {
    + {static} Group(childs:IEbnfElement<T>[]) : Group_t<T>
}
class "Group_t`1"<T> <<struct>> {
    + childs : IEbnfElement<T>[]
    + HasToken(t:T) : bool
    + ParseElement(ar:ArrayReader<TokenElement<T>>) : AstNode<T>
}
ParserModule +-- "Group_t`1"
"IEbnfElement`1" "<T>" <|-- "Group_t`1"
@enduml
