@startuml
class ParserModule <<static>> <<partial>> {
    + {static} Optional(childs:IEbnfElement<T>[]) : Optional_t<T>
}
class "Optional_t`1"<T> <<struct>> {
    + childs : IEbnfElement<T>[]
    + HasToken(t:T) : bool
    + ParseElement(ar:ArrayReader<TokenElement<T>>) : AstNode<T>
}
ParserModule +-- "Optional_t`1"
"IEbnfElement`1" "<T>" <|-- "Optional_t`1"
@enduml
