@startuml
class ParserModule <<static>> <<partial>> {
    + {static} RefRule(name:string) : RefRule_t<T>
}
class "RefRule_t`1"<T> <<struct>> {
    + name : string
    + HasToken(t:T) : bool
    + ParseElement(ar:ArrayReader<TokenElement<T>>) : AstNode<T>
}
ParserModule +-- "RefRule_t`1"
"IEbnfElement`1" "<T>" <|-- "RefRule_t`1"
@enduml
