@startuml
class ParserModule <<static>> <<partial>> {
    + {static} Rule(name:string, childs:IEbnfElement<T>[]) : Rule_t<T>
    + {static} Rule(name:string, token:T, childs:IEbnfElement<T>[]) : Rule_t<T>
}
class "Rule_t`1"<T> <<struct>> {
    + token : T
    + name : string
    + childs : IEbnfElement<T>[]
    + HasToken(t:T) : bool
    + ParseElement(rl:RuleList<T>, ast:AbstractSyntaxTree<T>) : AstNode<T>
}
ParserModule +-- "Rule_t`1"
"IEbnfElement`1" "<T>" <|-- "Rule_t`1"
@enduml
