@startuml
class ParserModule <<static>> <<partial>> {
    + {static} TK(token:T) : TK_t<T>
}
class "TK_t`1"<T> <<struct>> {
    + token : T
    + ParseElement(ar:ArrayReader<TokenElement<T>>) : AstNode<T>
}
ParserModule +-- "TK_t`1"
"IEbnfElement`1" "<T>" <|-- "TK_t`1"
@enduml
